#development:
#  adapter: sqlserver
#  database: BD_BARCO
#  username: datasync_user
#  password: 123456
#  host: 127.0.0.1
#  port: 1433
#  encoding: utf-8
 
development:
  adapter: jdbc
  #Tulio
  url: jdbc:jtds:sqlserver://10.211.55.3:1433/BICICLETA
  #Pedro
  #url: jdbc:jtds:sqlserver://10.0.0.104:1433/TESTE
  driver: net.sourceforge.jtds.jdbc.Driver
  username: datasync_user
  password: 123456
